services:
  clinicaltrials.api:
    image: clinicaltrials.api
    build:
      context: .
      dockerfile: src/ClinicalTrials.API/Dockerfile
    container_name: clinicaltrials.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=5000
    ports:
      - "5000:5000"
    depends_on:
      clinicaltrials.database:
        condition: service_healthy
  
  clinicaltrials.database:
    image: postgres:latest
    container_name: clinicaltrials.database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clinicaltrials
    volumes:
      - ./.containers/postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5